add step to migrate state file from single-customization to multi-customization

diff --git a/modules/aft-customizations/buildspecs/aft-account-customizations-terraform.yml b/modules/aft-customizations/buildspecs/aft-account-customizations-terraform.yml
--- a/modules/aft-customizations/buildspecs/aft-account-customizations-terraform.yml
+++ b/modules/aft-customizations/buildspecs/aft-account-customizations-terraform.yml
@@ -21,7 +21,7 @@ phases:
       - AFT_ADMIN_ROLE_ARN=arn:$AWS_PARTITION:iam::$AFT_MGMT_ACCOUNT:role/$AFT_ADMIN_ROLE_NAME
       - ROLE_SESSION_NAME=$(aws ssm get-parameter --name /aft/resources/iam/aft-session-name | jq --raw-output ".Parameter.Value")
       - |
-        # CodeBuild does not support arrays between steps (bizarre, YES), so must split the input every new step
+        # As of Aug 2025, CodeBuild does not support arrays between steps, so must split the input every new step
         CUSTOMIZATION_RAW=$(aws dynamodb get-item --table-name aft-request-metadata --key "{\"id\": {\"S\": \"$VENDED_ACCOUNT_ID\"}}" --attributes-to-get "account_customizations_name" | jq --raw-output ".Item.account_customizations_name.S")
         echo "Account customization value from DDB: ${CUSTOMIZATION_RAW}"
         # Split the customization on commas
@@ -30,10 +30,10 @@ phases:
         # Check if the first customization directory exists, then loop over all
         if [[ ${#CUSTOMIZATION_ARRAY[@]} -eq 0 ]]; then 
           echo "No customizations found, skipping setup."
-          exit 1 # TODO - Exit 0, this is acceptable
+          exit 0
         fi
         if [[ ! -d "$DEFAULT_PATH/${CUSTOMIZATION_ARRAY[0]}" ]]; then
-          echo "Error: ${CUSTOMIZATION_ARRAY[0]} directory does not exist"
+          echo "Error: ${CUSTOMIZATION_ARRAY[0]} is specified as an account customization but does not have a corresponding directory in the account customizations repo."
           exit 1
         fi
           
@@ -69,7 +69,7 @@ phases:
         # Install AFT Python Dependencies
         python3 -m venv $DEFAULT_PATH/aft-venv
         $DEFAULT_PATH/aft-venv/bin/pip install pip==22.1.2
-        $DEFAULT_PATH/aft-venv/bin/pip install jinja2-cli==0.7.0 Jinja2==3.0.1 MarkupSafe==2.0.1 boto3==1.18.56 requests==2.26.0
+        $DEFAULT_PATH/aft-venv/bin/pip install jinja2-cli==0.7.0 Jinja2==3.0.1 MarkupSafe==2.0.1 boto3==1.18.56 requests==2.26.0 # TODO - these should probably live in a requirements.txt file
 
       - |
         # Install API Helper Python Dependencies
@@ -114,27 +114,47 @@ phases:
   pre_build:
     on-failure: ABORT
     commands:
-      # TODO - but what about my existing `terraform.tfstate` file from previous versions of AFT? On the first run of this new version, it will be moved to a subfolder of the first account customiation
-      - |
-        # Destroy any customizations that were removed entirely -- make sure to destroy any references BEFORE deleting the customization from aft-account-customizations!!
-        IFS="," read -ra CUSTOMIZATION_ARRAY <<< "$CUSTOMIZATION_RAW"
-        TF_S3_BUCKET=$(aws ssm get-parameter --name "/aft/config/oss-backend/bucket-id" --query "Parameter.Value" --output text) 
-        CUSTOMIZATION_KEYS_ARRAY=$(aws s3api list-objects-v2 --bucket $TF_S3_BUCKET --prefix "${VENDED_ACCOUNT_ID}-aft-account-customizations/" --delimiter "/" --query "CommonPrefixes[].Prefix" --output text) # TODO - this approach does not support TFC, only S3-backed TF
-        echo "Array of existing keys in state bucket: $CUSTOMIZATION_KEYS_ARRAY"
-        # Loop over the CUSTOMIZATION_KEYS_ARRAY and create an array of customizations NOT in the CUSTOMIZATION_ARRAY. These resources will be tf-destroyed.
-        CUSTOMIZATIONS_TO_DESTROY=()
-        for KEY in ${CUSTOMIZATION_KEYS_ARRAY}; do
-          echo "This is the current key: $KEY"
-          JUST_THE_KEY_NO_PATH=$(echo ${KEY%/} | awk -F'/' '{print $NF}')
-          if [[ ! " ${CUSTOMIZATION_ARRAY[*]} " =~ " ${JUST_THE_KEY_NO_PATH} " ]]; then
-            CUSTOMIZATIONS_TO_DESTROY+=("$JUST_THE_KEY_NO_PATH")
-          else
-            echo "${JUST_THE_KEY_NO_PATH} is in the Active Customization Array ${CUSTOMIZATION_ARRAY[*]} so should not be destroyed."
+      - | 
+        # Migration check: look for existing `terraform.tfstate` file in root from single-account-customization versions of AFT and move them to a subfolder for the customization
+        RESPONSE=$(aws s3api head-object --bucket $TF_S3_BUCKET --key "${VENDED_ACCOUNT_ID}-aft-account-customizations/terraform.tfstate" >/dev/null 2>1; echo $?)
+        if [[ $RESPONSE != 254 ]]; then
+          IFS="," read -ra CUSTOMIZATION_ARRAY <<< "$CUSTOMIZATION_RAW"
+          if [[ ${#CUSTOMIZATION_ARRAY[@]} -eq 0 ]]; then
+            echo "WARNING: This account does not have any account customizations assigned to it. Skipping phase."
+            exit 0
           fi
-        done
-        echo "Customizations to destroy: $CUSTOMIZATIONS_TO_DESTROY"
-
+          if [[ ${#CUSTOMIZATION_ARRAY[@]} != 1 ]]; then
+            echo "ERROR: Expected 1 customization during migration of pre-upgrade terraform.tfstate, but found ${#CUSTOMIZATION_ARRAY[@]}"
+            exit 2
+          fi
+          aws s3 mv "s3://${TF_S3_BUCKET}/${VENDED_ACCOUNT_ID}-aft-account-customizations/terraform.tfstate" "s3://${TF_S3_BUCKET}/${VENDED_ACCOUNT_ID}-aft-account-customizations/${CUSTOMIZATION_ARRAY[0]}/terraform.tfstate"
+          echo "Moved existing terraform.tfstate file to subfolder /${CUSTOMIZATION_ARRAY[0]}."
+        fi
+      - |
+        # Destroy any customizations that were removed from the account; note, if removing the customization from AFT entirely, make sure to destroy any deployments of that customization BEFORE deleting the customization folder from aft-account-customizations!!
+        IFS="," read -ra CUSTOMIZATION_ARRAY <<< "$CUSTOMIZATION_RAW"
         if [ $TF_DISTRIBUTION = "oss" ]; then
+          TF_S3_BUCKET=$(aws ssm get-parameter --name "/aft/config/oss-backend/bucket-id" --query "Parameter.Value" --output text) 
+          CUSTOMIZATION_KEYS_ARRAY=$(aws s3api list-objects-v2 --bucket $TF_S3_BUCKET --prefix "${VENDED_ACCOUNT_ID}-aft-account-customizations/" --delimiter "/" --query "CommonPrefixes[].Prefix" --output text) # TODO - this approach does not support TFC, only S3-backed TF
+          if [[ "$CUSTOMIZATION_KEYS_ARRAY" = "None" ]] ; then
+            CUSTOMIZATION_KEYS_ARRAY=() # replace with an empty array instead of "None"
+          fi
+          echo "Array of existing keys in state bucket: $CUSTOMIZATION_KEYS_ARRAY"
+
+          # Loop over the CUSTOMIZATION_KEYS_ARRAY and create an array of customizations NOT in the CUSTOMIZATION_ARRAY. These resources will be tf-destroyed.
+          CUSTOMIZATIONS_TO_DESTROY=()
+          for KEY in ${CUSTOMIZATION_KEYS_ARRAY}; do
+            JUST_THE_KEY_NO_PATH=$(echo ${KEY%/} | awk -F'/' '{print $NF}')
+            if [[ ! " ${CUSTOMIZATION_ARRAY[*]} " =~ " ${JUST_THE_KEY_NO_PATH} " ]]; then
+              CUSTOMIZATIONS_TO_DESTROY+=("$JUST_THE_KEY_NO_PATH")
+              echo "${JUST_THE_KEY_NO_PATH} is NOT in the Active Customization Array ${CUSTOMIZATION_ARRAY[*]} so added to list to be destroyed."
+            else
+              echo "${JUST_THE_KEY_NO_PATH} is in the Active Customization Array ${CUSTOMIZATION_ARRAY[*]} so should not be destroyed."
+            fi
+          done
+          echo "Customizations to destroy: $CUSTOMIZATIONS_TO_DESTROY"
+
+
           for CUSTOMIZATION_KEY in "${CUSTOMIZATIONS_TO_DESTROY[@]}"; do
             source $DEFAULT_PATH/api-helpers-venv/bin/activate
             export AWS_PROFILE=aft-target
@@ -166,7 +186,7 @@ phases:
             /opt/aft/bin/terraform init -no-color
             /opt/aft/bin/terraform destroy -no-color --auto-approve
             unset AWS_PROFILE
-            # Delete all versions of the object so that the bucket is clean - TODO - validate this approach, then implement
+            # Delete all versions of the object so that the bucket is clean - TODO - AFT doesn't currently have permissions to delete versions in S3.
             # echo "Deleting all versions of state keys in $TF_S3_KEY"
             # ALL_VERSIONS=$(aws s3api list-object-versions --bucket "$TF_S3_BUCKET" --prefix "$TF_S3_KEY" | jq -r '.Versions[].VersionId')
             # for VERSION in $ALL_VERSIONS; do
@@ -174,6 +194,7 @@ phases:
             # done
           done
         else
+          # TODO - this is the non-OSS (TFC) branch, which needs any removed customizations deleted as well
           for CUSTOMIZATION_KEY in "${CUSTOMIZATIONS_TO_DESTROY[@]}"; do
             source $DEFAULT_PATH/api-helpers-venv/bin/activate
             export AWS_PROFILE=aft-target
@@ -214,12 +235,11 @@ phases:
       - |
         if [ $TF_DISTRIBUTION = "oss" ]; then
           IFS="," read -ra CUSTOMIZATION_ARRAY <<< "$CUSTOMIZATION_RAW"
-          echo "Customization Array: $CUSTOMIZATION_ARRAY"
           for CUSTOMIZATION in "${CUSTOMIZATION_ARRAY[@]}"; do
             echo "Deploying Customization ${CUSTOMIZATION}"
             source $DEFAULT_PATH/api-helpers-venv/bin/activate
             export AWS_PROFILE=aft-target
-            $DEFAULT_PATH/$CUSTOMIZATION/api_helpers/pre-api-helpers.sh # if not found, check that line endings are LF not CRLF
+            $DEFAULT_PATH/$CUSTOMIZATION/api_helpers/pre-api-helpers.sh # note: if file not found, check that line endings are LF not CRLF
             unset AWS_PROFILE
             source $DEFAULT_PATH/aft-venv/bin/activate
             TF_BACKEND_REGION=$(aws ssm get-parameter --name "/aft/config/oss-backend/primary-region" --query "Parameter.Value" --output text)
@@ -248,7 +268,7 @@ phases:
             /opt/aft/bin/terraform apply -no-color --auto-approve
           done
         fi
-      # Apply Customizations - TFC flavor
+      # Apply Customizations - TFC flavor - TODO - this has not been tested and needs to support the multi-customization model
       - |
         if [ ! $TF_DISTRIBUTION = "oss" ]; then
           IFS="," read -ra CUSTOMIZATION_ARRAY <<< "$CUSTOMIZATION_RAW"
